// lib/checklistData.ts
// জমি কেনার পুরো প্রক্রিয়ার ৮টি ধাপ এবং প্রতিটি ধাপের চেকলিস্ট আইটেম।

import { ChecklistStep } from "./types";

export const CHECKLIST_STEPS: ChecklistStep[] = [
  {
    id: 1,
    title: "প্রাথমিক তথ্য সংগ্রহ",
    shortTitle: "প্রাথমিক তথ্য",
    description:
      "জমি সম্পর্কে মৌলিক তথ্য সংগ্রহ করুন। এই তথ্য ভুল হলে পরের সব যাচাই ভুল হয়ে যাবে।",
    items: [
      {
        id: "step1-mouza",
        label: "জমির মৌজা নাম লিখেছেন",
        guidance: "মৌজা নাম স্থানীয় ভূমি অফিস বা দলিলে পাওয়া যাবে।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step1-dag",
        label: "দাগ নম্বর লিখেছেন",
        guidance: "খতিয়ান বা পর্চায় দাগ নম্বর উল্লেখ থাকে।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step1-khatian",
        label: "খতিয়ান নম্বর লিখেছেন",
        guidance: "CS/SA/RS/BS — যে খতিয়ান অনুযায়ী যাচাই করবেন তার নম্বর।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step1-quantity",
        label: "জমির পরিমাণ (শতাংশ/কাঠা) লিখেছেন",
        guidance: "দলিল ও খতিয়ানের পরিমাণ মিলছে কিনা পরে যাচাই করবেন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step1-class",
        label: "জমির শ্রেণি নির্বাচন করেছেন (কৃষি / অকৃষি / বসতবাড়ি)",
        guidance: "শ্রেণি অনুযায়ী রেজিস্ট্রেশন ফি ও ব্যবহারের নিয়ম ভিন্ন হয়।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step1-seller",
        label: "বিক্রেতার পূর্ণ নাম ও NID নম্বর সংগ্রহ করেছেন",
        guidance: "NID এর কপি সংগ্রহ করে রাখুন, পরে যাচাইয়ে লাগবে।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step1-address",
        label: "জমির বর্তমান অবস্থান (ঠিকানা) লিখেছেন",
        guidance: "সরেজমিনে পরিদর্শনের সময় এই ঠিকানা কাজে লাগবে।",
        blocking: false,
        canFlagIssue: false,
      },
    ],
  },
  {
    id: 2,
    title: "মালিকানা যাচাই (Due Diligence)",
    shortTitle: "মালিকানা যাচাই",
    description:
      "এই ধাপ সবচেয়ে গুরুত্বপূর্ণ। এখানে কোনো সমস্যা পেলে কেনা থেকে বিরত থাকার পরামর্শ দেওয়া হবে।",
    items: [
      {
        id: "step2-original-deed",
        label: "বিক্রেতার মূল দলিল (সাফ-কবলা) দেখেছেন",
        guidance: "মূল কপি দেখুন, ফটোকপি নয়।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step2-baya-deed",
        label: "অন্তত ২৫ বছরের বায়া দলিল সংগ্রহ করেছেন",
        guidance: "মালিকানার ধারাবাহিকতা যাচাইয়ের জন্য পুরনো দলিলগুলো লাগবে।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step2-deed-chain",
        label: "দলিলের চেইন (মালিকানা ধারাবাহিকতা) ভালোভাবে মিলিয়েছেন",
        guidance: "এক মালিক থেকে আরেক মালিকে হস্তান্তরের প্রতিটি ধাপ ফাঁকা না থাকা জরুরি।",
        blocking: true,
        canFlagIssue: true,
      },
      {
        id: "step2-subregistry-check",
        label: "সাব-রেজিস্ট্রি অফিসে দলিলের ভলিউম নম্বর ও তারিখ যাচাই করেছেন",
        guidance: "দলিল আসল কিনা নিশ্চিত করতে সাব-রেজিস্ট্রি অফিসের রেকর্ডের সাথে মিলিয়ে দেখুন।",
        blocking: true,
        canFlagIssue: true,
      },
      {
        id: "step2-cs-khatian",
        label: "CS খতিয়ান সংগ্রহ/চেক করেছেন",
        guidance: "সবচেয়ে পুরনো জরিপ রেকর্ড।",
        blocking: false,
        canFlagIssue: false,
      },
      {
        id: "step2-sa-khatian",
        label: "SA খতিয়ান সংগ্রহ/চেক করেছেন",
        guidance: "CS এর পরের জরিপ রেকর্ড।",
        blocking: false,
        canFlagIssue: false,
      },
      {
        id: "step2-rs-khatian",
        label: "RS খতিয়ান সংগ্রহ/চেক করেছেন",
        guidance: "SA এর পরের জরিপ রেকর্ড।",
        blocking: false,
        canFlagIssue: false,
      },
      {
        id: "step2-bs-khatian",
        label: "সর্বশেষ BS / City খতিয়ান সংগ্রহ/চেক করেছেন",
        guidance: "সর্বশেষ ও সবচেয়ে গুরুত্বপূর্ণ খতিয়ান।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step2-name-match",
        label: "খতিয়ানে বিক্রেতার নাম মিলছে",
        guidance: "নাম না মিললে বিক্রেতা প্রকৃত মালিক নাও হতে পারেন।",
        blocking: true,
        canFlagIssue: true,
      },
      {
        id: "step2-mutation",
        label: "বিক্রেতার নামে সর্বশেষ নামজারি (Mutation) হয়েছে",
        guidance: "নামজারি ছাড়া মালিকানা অসম্পূর্ণ ধরা হয়।",
        blocking: true,
        canFlagIssue: true,
      },
      {
        id: "step2-landgov-check",
        label: "land.gov.bd পোর্টালে নামজারি যাচাই করেছেন",
        guidance: "অনলাইনে land.gov.bd এ গিয়ে নামজারি খতিয়ান যাচাই করুন।",
        blocking: false,
        canFlagIssue: false,
      },
      {
        id: "step2-tax-receipt",
        label: "হাল সনের খাজনা পরিশোধিত রশিদ দেখেছেন",
        guidance: "সর্বশেষ বছরের খাজনা বকেয়া থাকলে তা মিটিয়ে নিতে হবে।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step2-tollash",
        label: "সাব-রেজিস্ট্রি অফিসে ১২-১৫ বছরের তল্লাশি দিয়েছেন",
        guidance: "তল্লাশির মাধ্যমে বন্ধক, মামলা বা অন্য বিক্রয়ের তথ্য বের হয়ে আসে।",
        blocking: true,
        canFlagIssue: true,
      },
      {
        id: "step2-no-mortgage-case",
        label: "কোনো বন্ধক / বায়না / মামলা নেই নিশ্চিত করেছেন",
        guidance: "থাকলে জমি কেনা থেকে বিরত থাকাই নিরাপদ।",
        blocking: true,
        canFlagIssue: true,
      },
      {
        id: "step2-site-visit",
        label: "জমি সরেজমিনে দেখেছেন",
        guidance: "কাগজে যা লেখা আছে বাস্তবে তা মিলছে কিনা দেখুন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step2-boundary-match",
        label: "সীমানা ও চৌহদ্দি মিলিয়েছেন",
        guidance: "দলিলে উল্লেখিত চৌহদ্দির সাথে বাস্তবের সীমানা মিলিয়ে দেখুন।",
        blocking: true,
        canFlagIssue: true,
      },
      {
        id: "step2-no-acquisition",
        label: "কোনো সরকারি অধিগ্রহণ বা নোটিশ নেই নিশ্চিত করেছেন",
        guidance: "স্থানীয় ভূমি অফিসে খোঁজ নিন।",
        blocking: true,
        canFlagIssue: true,
      },
      {
        id: "step2-poa-check",
        label: "পাওয়ার অফ অ্যাটর্নি থাকলে সেটি যাচাই করেছেন",
        guidance: "পাওয়ার অফ অ্যাটর্নি রেজিস্ট্রার্ড ও বৈধ কিনা যাচাই করুন।",
        blocking: false,
        canFlagIssue: true,
      },
    ],
  },
  {
    id: 3,
    title: "বায়না চুক্তি",
    shortTitle: "বায়না চুক্তি",
    description: "ক্রয়ের শর্তাবলী নির্ধারণ করে একটি বায়না চুক্তি সম্পন্ন করুন।",
    items: [
      {
        id: "step3-deed-created",
        label: "বায়না দলিল তৈরি করেছেন",
        guidance: "আইনজীবী বা দলিল লেখক দিয়ে তৈরি করানো ভালো।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step3-full-desc",
        label: "জমির সম্পূর্ণ বিবরণ বায়নায় লিখেছেন",
        guidance: "মৌজা, দাগ, খতিয়ান, পরিমাণ — সব উল্লেখ করুন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step3-price-advance",
        label: "ক্রয়মূল্য ও অগ্রিম টাকার পরিমাণ উল্লেখ করেছেন",
        guidance: "দুই পক্ষের সম্মত মূল্য স্পষ্টভাবে লিখুন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step3-payment-deadline",
        label: "বাকি টাকা পরিশোধের সময়সীমা লিখেছেন",
        guidance: "নির্দিষ্ট তারিখ উল্লেখ করা ভালো।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step3-possession-date",
        label: "দখল হস্তান্তরের তারিখ লিখেছেন",
        guidance: "কবে দখল বুঝিয়ে দেওয়া হবে তা নির্ধারণ করুন।",
        blocking: false,
        canFlagIssue: false,
      },
      {
        id: "step3-signatures",
        label: "উভয় পক্ষ স্বাক্ষর করেছেন",
        guidance: "সাক্ষীসহ স্বাক্ষর করানো নিরাপদ।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step3-advance-receipt",
        label: "অগ্রিম টাকার রসিদ নিয়েছেন",
        guidance: "টাকা লেনদেনের প্রমাণ হিসেবে রসিদ সংরক্ষণ করুন।",
        blocking: true,
        canFlagIssue: false,
      },
    ],
  },
  {
    id: 4,
    title: "বিক্রয় দলিল তৈরি",
    shortTitle: "বিক্রয় দলিল",
    description: "চূড়ান্ত বিক্রয় দলিলের খসড়া প্রস্তুত করুন।",
    items: [
      {
        id: "step4-draft",
        label: "দলিল লেখক/আইনজীবী দিয়ে খসড়া তৈরি করেছেন",
        guidance: "অভিজ্ঞ দলিল লেখক দিয়ে করানো ভুল এড়াতে সাহায্য করবে।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step4-parties-info",
        label: "ক্রেতা ও বিক্রেতার পূর্ণ তথ্য (নাম, ঠিকানা, NID) সঠিক আছে",
        guidance: "ছোট ভুলও পরে রেজিস্ট্রেশনে সমস্যা করতে পারে।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step4-schedule",
        label: "জমির তফসিল (মৌজা, দাগ, খতিয়ান, পরিমাণ, চৌহদ্দি) সঠিক আছে",
        guidance: "ধাপ ১ ও ২ এর তথ্যের সাথে মিলিয়ে দেখুন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step4-price-written",
        label: "ক্রয়মূল্য সঠিকভাবে লেখা আছে",
        guidance: "স্ট্যাম্প শুল্ক এই মূল্যের উপর নির্ভর করবে।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step4-possession-clause",
        label: "দখল হস্তান্তরের ঘোষণা আছে",
        guidance: "দলিলে স্পষ্টভাবে দখল হস্তান্তরের কথা উল্লেখ থাকা উচিত।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step4-witnesses",
        label: "সাক্ষীদের নাম ও স্বাক্ষরের জায়গা রাখা আছে",
        guidance: "সাধারণত ২ জন সাক্ষী প্রয়োজন হয়।",
        blocking: true,
        canFlagIssue: false,
      },
    ],
  },
  {
    id: 5,
    title: "স্ট্যাম্প ও ফি পরিশোধ",
    shortTitle: "স্ট্যাম্প ও ফি",
    description: "রেজিস্ট্রেশনের আগে প্রয়োজনীয় সব সরকারি ফি হিসাব করে পরিশোধ করুন।",
    items: [
      {
        id: "step5-stamp-duty",
        label: "স্ট্যাম্প শুল্কের পরিমাণ হিসাব করেছেন",
        guidance: "জমির শ্রেণি ও মূল্যের উপর ভিত্তি করে হিসাব করুন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step5-reg-fee",
        label: "রেজিস্ট্রেশন ফি হিসাব করেছেন",
        guidance: "সরকারি নির্ধারিত হার অনুযায়ী হিসাব করুন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step5-local-tax",
        label: "স্থানীয় সরকার কর / অন্যান্য ফি হিসাব করেছেন",
        guidance: "এলাকাভেদে অতিরিক্ত কর প্রযোজ্য হতে পারে।",
        blocking: false,
        canFlagIssue: false,
      },
      {
        id: "step5-treasury-deposit",
        label: "ট্রেজারি/ব্যাংকে টাকা জমা দিয়েছেন",
        guidance: "নির্ধারিত ব্যাংক শাখা বা ট্রেজারিতে জমা দিন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step5-challans",
        label: "সব চালান সংগ্রহ করেছেন",
        guidance: "রেজিস্ট্রেশনের দিন সাথে নিয়ে যেতে হবে।",
        blocking: true,
        canFlagIssue: false,
      },
    ],
  },
  {
    id: 6,
    title: "সাব-রেজিস্ট্রি অফিসে রেজিস্ট্রেশন",
    shortTitle: "রেজিস্ট্রেশন",
    description: "দলিল রেজিস্ট্রেশনের জন্য সাব-রেজিস্ট্রি অফিসে উপস্থিত হোন।",
    items: [
      {
        id: "step6-office-select",
        label: "সঠিক সাব-রেজিস্ট্রি অফিস নির্বাচন করেছেন",
        guidance: "জমির অবস্থান অনুযায়ী সংশ্লিষ্ট অফিস নির্বাচন করুন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step6-buyer-present",
        label: "ক্রেতা উপস্থিত আছেন",
        guidance: "প্রয়োজনে বৈধ প্রতিনিধিও উপস্থিত থাকতে পারেন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step6-seller-present",
        label: "বিক্রেতা (বা বৈধ পাওয়ার অফ অ্যাটর্নি) উপস্থিত আছেন",
        guidance: "পাওয়ার অফ অ্যাটর্নি হলে তার মূল কপি সাথে থাকা জরুরি।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step6-witnesses-present",
        label: "কমপক্ষে ২ জন সাক্ষী উপস্থিত আছেন",
        guidance: "সাক্ষীদের NID সাথে রাখুন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step6-documents",
        label: "সব প্রয়োজনীয় কাগজপত্র সাথে নিয়েছেন",
        guidance: "দলিল, চালান, NID, ছবি ইত্যাদি একসাথে গুছিয়ে রাখুন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step6-signing",
        label: "দলিল স্বাক্ষর, আঙুলের ছাপ ও ছবি সম্পন্ন হয়েছে",
        guidance: "রেজিস্ট্রি অফিসের নির্ধারিত প্রক্রিয়া অনুযায়ী সম্পন্ন করুন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step6-reg-number",
        label: "রেজিস্ট্রেশন নম্বর পেয়েছেন",
        guidance: "এই নম্বরটি ভবিষ্যতে দলিলের রেফারেন্স হিসেবে ব্যবহৃত হবে।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step6-certified-copy",
        label: "সার্টিফায়েড কপি সংগ্রহ করেছেন",
        guidance: "নামজারির আবেদনে এই কপি প্রয়োজন হবে।",
        blocking: true,
        canFlagIssue: false,
      },
    ],
  },
  {
    id: 7,
    title: "নামজারি (Mutation)",
    shortTitle: "নামজারি",
    description: "নিজের নামে খতিয়ান হালনাগাদ করতে নামজারির আবেদন করুন।",
    items: [
      {
        id: "step7-application",
        label: "নামজারির আবেদন করেছেন (অনলাইন বা অফিসে)",
        guidance: "land.gov.bd থেকে অনলাইনেও আবেদন করা যায়।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step7-registered-deed",
        label: "রেজিস্ট্রার্ড দলিল জমা দিয়েছেন",
        guidance: "সার্টিফায়েড কপি জমা দিতে হবে।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step7-previous-khatian",
        label: "পূর্বের খতিয়ান জমা দিয়েছেন",
        guidance: "বিক্রেতার নামে থাকা খতিয়ানের কপি জমা দিন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step7-tax-receipt-mutation",
        label: "খাজনার রশিদ জমা দিয়েছেন",
        guidance: "সর্বশেষ পরিশোধিত রশিদ জমা দিন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step7-nid",
        label: "NID জমা দিয়েছেন",
        guidance: "আবেদনকারীর NID এর সত্যায়িত কপি জমা দিন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step7-field-survey",
        label: "ফিল্ড সার্ভে সম্পন্ন হয়েছে (প্রয়োজন হলে)",
        guidance: "ভূমি অফিসের কর্মকর্তা সরেজমিনে যাচাই করতে পারেন।",
        blocking: false,
        canFlagIssue: false,
      },
      {
        id: "step7-mutation-order",
        label: "নামজারি অর্ডার পেয়েছেন",
        guidance: "এই অর্ডার নামজারি অনুমোদনের প্রমাণ।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step7-name-updated",
        label: "নতুন খতিয়ানে নিজের নাম এসেছে",
        guidance: "খতিয়ান কপি সংগ্রহ করে নিশ্চিত হোন।",
        blocking: true,
        canFlagIssue: false,
      },
    ],
  },
  {
    id: 8,
    title: "দখল গ্রহণ ও চূড়ান্ত কাজ",
    shortTitle: "দখল গ্রহণ",
    description: "প্রক্রিয়ার শেষ ধাপ — জমির প্রকৃত দখল বুঝে নিন ও কাগজপত্র সংরক্ষণ করুন।",
    items: [
      {
        id: "step8-possession",
        label: "জমির দখল নিয়েছেন",
        guidance: "বিক্রেতার কাছ থেকে আনুষ্ঠানিকভাবে দখল বুঝে নিন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step8-boundary-mark",
        label: "সীমানা চিহ্নিত করেছেন",
        guidance: "সীমানা পিলার বা চিহ্ন বসিয়ে নিন।",
        blocking: false,
        canFlagIssue: false,
      },
      {
        id: "step8-tax-start",
        label: "নিজের নামে খাজনা দেওয়া শুরু করেছেন",
        guidance: "প্রতি বছর নিয়মিত খাজনা পরিশোধ করুন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step8-safe-documents",
        label: "সব মূল কাগজপত্র নিরাপদ জায়গায় রেখেছেন",
        guidance: "মূল দলিল, খতিয়ান, রশিদ ইত্যাদি একসাথে সংরক্ষণ করুন।",
        blocking: true,
        canFlagIssue: false,
      },
      {
        id: "step8-conversion",
        label: "প্রয়োজন হলে ব্যবহার পরিবর্তন (Conversion) করেছেন",
        guidance: "কৃষি জমি অকৃষি কাজে ব্যবহার করলে কনভার্শন প্রয়োজন হতে পারে।",
        blocking: false,
        canFlagIssue: false,
      },
    ],
  },
];